### ISSUE TITLE
Add installation guide

### ISSUE THREAD

**Issue by Terbiy** [ghivert/modular-styles#2]
Hello!
Thank you for developing `modular-styles`! Using `PostCSS` is also a great idea. I want to use it with [day8/re-frame-template](https://github.com/day8/re-frame-template), but have a very little idea how to install and set up `modular-styles` there correctly. Could you please add installation guide?

**Comment by ghivert** [comment]
Hi Terbiy!

Thank you for interest! You can have a quick idea here: [ghivert/re-frame-template](https://github.com/ghivert/re-frame-template) which is my own installation setup for re-frame, using bare re-frame, shadow-cljs and modular-styles.
I'll do a better config script when I'll have time. Feel free to ask more questions if needed. `modular-styles` need more polish, but it's on the roadmap (like infering src directory, etc.)

**Comment by Terbiy** [comment]
I'll investigate it, thank you, @ghivert! CSS modules seem for me one of the most necessary CSS technologies nowadays, so I am also interested in using your library. If successful, I'll try to write the installation guide by myself and make the PR.

**Comment by Terbiy** [comment]
Created a PR: https://github.com/ghivert/modular-styles/pull/4.

**Comment by ghivert** [comment]
Woaw, so cool ! I’ll merge it and add some info if I think about something soon!

Thank you very much!

**Comment by ghivert** [comment]
That seems good to me now. What do you think about it?

**Comment by Terbiy** [comment]
I think this is good enough for now, especially in combination with example in the template. New users with their perspective will help make it even better!🙃

**Comment by Terbiy** [comment]
@ghivert, don't you need `--dev` flag when using Yarn for installation?🤔

**Comment by ghivert** [comment]
Yes, you’re totally right. I’ll change it right now. :)

Thank you very much!
