### ISSUE TITLE
Some options can not be overridden

### ISSUE THREAD

**Issue by P233** [ghivert/modular-styles#5]
When I was trying to customize some options, such as `extension` `bundlePath`, I found those options always use the default value rather than my custom value. So I did some tests and found that the `convert-options` function always returns `undefined` for `extension` `bundleName` `bundlePath` `tempCSS` four options. This is probably caused by the advanced optimization renamed the object keys, and using `goog.object/get` to access the JS object keys can fix this issue. I am new to ClojureScript, not sure if it is the best solution.

Thank you for creating this package, it is awesome!

**Comment by ghivert** [comment]
Thank you very much! I'll take a look at this quickly (probably today or tomorrow) and I’ll let you know.

If you want you can try to PR?

**Comment by P233** [comment]
Thanks, I just created a PR :)

**Comment by ghivert** [comment]
Sorry for taking so long time… :( 

I had a computer problem making me unable to work on this project. Your changes are merged and a new version is releasing right now. :)
